(function(){
  const view=document.getElementById('adminView');
  let ready=false;
  const css=`.friend-admin-panel{margin-top:18px}.friend-admin-heading{display:flex;justify-content:space-between;align-items:flex-start;margin-bottom:16px}.friend-admin-form{display:grid;grid-template-columns:1fr 1fr;gap:0 14px;border-bottom:1px solid var(--line);padding-bottom:17px;margin-bottom:4px}.friend-admin-form label.wide{grid-column:1/-1}.friend-admin-list{display:grid}.friend-admin-row{display:grid;grid-template-columns:34px 1fr 110px 80px;gap:12px;align-items:center;border-bottom:1px solid var(--line);padding:13px 0}.friend-admin-row img{width:28px;height:28px;border-radius:7px;object-fit:cover;border:1px solid var(--line)}.friend-admin-row strong,.friend-admin-row small{display:block;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.friend-admin-row strong{font-size:13px}.friend-admin-row small{font-size:10px;color:var(--muted);margin-top:3px}.friend-admin-actions{display:flex;justify-content:flex-end;gap:10px}.friend-admin-actions button{border:0;background:transparent;color:var(--muted);font-size:11px}.friend-admin-actions .danger:hover{color:var(--danger)}@media(max-width:800px){.friend-admin-form{grid-template-columns:1fr}.friend-admin-form label.wide{grid-column:auto}.friend-admin-row{grid-template-columns:34px 1fr 70px}.friend-admin-row .friend-admin-url{display:none}}`;
  function addStyle(){if(document.getElementById('friendAdminStyle'))return;const style=document.createElement('style');style.id='friendAdminStyle';style.textContent=css;document.head.appendChild(style);}
  async function api(url,options={}){const response=await fetch(url,{headers:{'Content-Type':'application/json',...(options.headers||{})},...options});let data={};try{data=await response.json();}catch(_){}if(!response.ok)throw Error(data.error||'请求失败');return data;}
  function mount(){if(ready||!view||view.classList.contains('is-hidden'))return;ready=true;addStyle();const section=document.getElementById('settingsSection');if(!section)return;section.insertAdjacentHTML('beforeend',`<div class="panel friend-admin-panel" id="friendAdminPanel"><div class="friend-admin-heading"><div><p class="admin-kicker">LINKS / FRIENDS</p><h3>友链管理</h3></div><button type="button" class="primary-btn compact" id="friendNewBtn">+ 新增友链</button></div><form id="friendLinkForm" class="friend-admin-form is-hidden"><input type="hidden" name="id"/><label>网站名称<input name="name" required placeholder="例如：rain-lei · GitHub"/></label><label>网站地址<input name="url" type="url" required placeholder="https://example.com"/></label><label>头像地址<input name="avatar" type="url" placeholder="留空则自动取 favicon"/></label><label>排序<input name="sort_order" type="number" value="0"/></label><label class="wide">一句话介绍<input name="description" placeholder="网站简介或作者说明"/></label><div class="form-actions wide"><span id="friendFormError" class="error-text"></span><button type="button" class="ghost-btn" id="friendCancelBtn">取消</button><button class="primary-btn compact" type="submit">保存友链</button></div></form><div id="friendAdminList" class="friend-admin-list"></div></div>`);const form=document.getElementById('friendLinkForm'),list=document.getElementById('friendAdminList');let links=[];function render(){list.innerHTML=links.map(link=>`<div class="friend-admin-row"><img src="${link.avatar||'https://www.google.com/s2/favicons?domain='+encodeURIComponent(link.url)+'&sz=64'}" alt=""/><div><strong>${link.name}</strong><small>${link.description||link.url}</small></div><span class="status-pill ${link.enabled?'published':'draft'}">${link.enabled?'展示中':'已隐藏'}</span><div class="friend-admin-actions"><button type="button" data-friend-edit="${link.id}">编辑</button><button type="button" class="danger" data-friend-delete="${link.id}">删除</button></div></div>`).join('')||'<p class="empty-state">还没有友链，先添加一个吧。</p>';}
  async function load(){try{links=await api('/api/admin/friend-links');render();}catch(error){list.innerHTML=`<p class="empty-state">${error.message}</p>`;}}
  function open(link){form.classList.remove('is-hidden');form.reset();form.id.value=link?.id||'';if(link){form.name.value=link.name;form.url.value=link.url;form.avatar.value=link.avatar;form.sort_order.value=link.sort_order;form.description.value=link.description;}form.name.focus();}function close(){form.classList.add('is-hidden');}
  document.getElementById('friendNewBtn').addEventListener('click',()=>open());document.getElementById('friendCancelBtn').addEventListener('click',close);form.addEventListener('submit',async event=>{event.preventDefault();const data=Object.fromEntries(new FormData(form));const id=data.id;delete data.id;try{await api(id?`/api/admin/friend-links/${id}`:'/api/admin/friend-links',{method:id?'PUT':'POST',body:JSON.stringify(data)});close();load();}catch(error){document.getElementById('friendFormError').textContent=error.message;}});list.addEventListener('click',async event=>{const edit=event.target.closest('[data-friend-edit]');if(edit)open(links.find(x=>String(x.id)===edit.dataset.friendEdit));const del=event.target.closest('[data-friend-delete]');if(del&&confirm('确认删除这个友链？')){await api(`/api/admin/friend-links/${del.dataset.friendDelete}`,{method:'DELETE'});load();}});load();}
  const observer=new MutationObserver(mount);if(view)observer.observe(view,{attributes:true,attributeFilter:['class']});mount();
})();
