(function(){
  let posts = window.blogPosts || [];
  const grid = document.getElementById('postGrid');
  const chips = [...document.querySelectorAll('.filter-chip')];
  const categoryBar = document.querySelector('.category-bar');
  const searchModal = document.getElementById('searchModal');
  const searchInput = document.getElementById('searchInput');
  const searchResults = document.getElementById('searchResults');
  const categoryWords = { study: 'LEARN', life: 'LIVE', entertainment: 'PLAY' };
  let filterIndicator;
  function refreshFilterIndicator(){if(!filterIndicator||!categoryBar)return;const active=categoryBar.querySelector('.filter-chip.is-selected');if(!active)return;const barRect=categoryBar.getBoundingClientRect(),chipRect=active.getBoundingClientRect();filterIndicator.style.width=`${chipRect.width}px`;filterIndicator.style.height=`${chipRect.height}px`;filterIndicator.style.transform=`translate(${chipRect.left-barRect.left}px,${chipRect.top-barRect.top}px)`;}
  function setupFilterIndicator(){if(!categoryBar)return;filterIndicator=document.createElement('span');filterIndicator.className='filter-indicator';filterIndicator.setAttribute('aria-hidden','true');categoryBar.prepend(filterIndicator);requestAnimationFrame(refreshFilterIndicator);window.addEventListener('resize',refreshFilterIndicator);}
  function postCard(post,index){return `<article class="post-card reveal" data-category="${post.category}" style="--delay:${index*55}ms"><a class="post-visual ${post.accent}" href="article.html?id=${post.id}" aria-label="阅读：${post.title}"><span class="visual-label">${post.categoryLabel}</span><span class="visual-number">${String(index+1).padStart(2,'0')}</span><span class="visual-shape"></span><span class="visual-word">${categoryWords[post.category]||'NOTE'}</span></a><div class="post-info"><div class="post-meta"><span>${post.date}</span><span>${post.read}</span></div><h3><a href="article.html?id=${post.id}">${post.title}</a></h3><p>${post.excerpt}</p><a class="card-link" href="article.html?id=${post.id}">阅读全文 <span>↗</span></a></div></article>`;}
  function updateCategoryCounts(){chips.forEach(chip=>{const filter=chip.dataset.filter;const count=filter==='all'?posts.length:posts.filter(post=>post.category===filter).length;const countElement=chip.querySelector('span');if(countElement)countElement.textContent=String(count);});}
  function renderPosts(filter='all'){updateCategoryCounts();if(!grid)return;const visible=filter==='all'?posts:posts.filter(p=>p.category===filter);grid.innerHTML=visible.map(postCard).join('');requestAnimationFrame(()=>{refreshFilterIndicator();document.querySelectorAll('.post-card.reveal').forEach(el=>el.classList.add('is-visible'));});}
  function applySettings(settings){if(!settings)return;document.querySelectorAll('[data-setting="siteName"]').forEach(el=>el.textContent=settings.siteName||el.textContent);document.querySelectorAll('[data-setting="intro"]').forEach(el=>el.textContent=settings.intro||el.textContent);document.querySelectorAll('[data-setting="siteEmail"]').forEach(el=>{el.textContent=settings.siteEmail||el.textContent;el.href=`mailto:${settings.siteEmail||'hello@linmo.studio'}`;});if(settings.siteName)document.title=`${settings.siteName} · 个人博客`;}
  async function loadRemoteData(){try{const response=await fetch('/api/posts');if(!response.ok)throw new Error();const remote=await response.json();if(Array.isArray(remote))posts=remote;renderPosts(document.querySelector('.filter-chip.is-selected')?.dataset.filter||'all');const settings=await fetch('/api/settings');if(settings.ok)applySettings(await settings.json());}catch(_){renderPosts();}}
  setupFilterIndicator();renderPosts();loadRemoteData();
  chips.forEach(chip=>chip.addEventListener('click',()=>{chips.forEach(c=>c.classList.remove('is-selected'));chip.classList.add('is-selected');refreshFilterIndicator();renderPosts(chip.dataset.filter);}));
  if(localStorage.getItem('linmo-theme')==='dark')document.body.classList.add('dark');const themeIcon=document.getElementById('themeIcon');const updateThemeIcon=()=>{if(themeIcon)themeIcon.textContent=document.body.classList.contains('dark')?'☾':'☼';};updateThemeIcon();document.getElementById('themeToggle')?.addEventListener('click',()=>{document.body.classList.toggle('dark');localStorage.setItem('linmo-theme',document.body.classList.contains('dark')?'dark':'light');updateThemeIcon();});
  const menuToggle=document.getElementById('menuToggle'),mobileNav=document.getElementById('mobileNav');menuToggle?.addEventListener('click',()=>{const open=mobileNav.classList.toggle('is-open');menuToggle.setAttribute('aria-expanded',String(open));mobileNav.setAttribute('aria-hidden',String(!open));});mobileNav?.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{mobileNav.classList.remove('is-open');menuToggle.setAttribute('aria-expanded','false');}));
  const header=document.querySelector('.site-header');const updateHeader=()=>header?.classList.toggle('is-scrolled',window.scrollY>18);updateHeader();window.addEventListener('scroll',updateHeader,{passive:true});
  grid?.addEventListener('pointermove',event=>{const visual=event.target.closest('.post-visual');if(!visual)return;const rect=visual.getBoundingClientRect();visual.style.setProperty('--spotlight-x',`${event.clientX-rect.left}px`);visual.style.setProperty('--spotlight-y',`${event.clientY-rect.top}px`);});grid?.addEventListener('pointerleave',event=>{const visual=event.target.closest?.('.post-visual');visual?.style.removeProperty('--spotlight-x');visual?.style.removeProperty('--spotlight-y');},true);
  function openSearch(){searchModal.classList.add('is-open');searchModal.setAttribute('aria-hidden','false');setTimeout(()=>searchInput?.focus(),80);}function closeSearch(){searchModal.classList.remove('is-open');searchModal.setAttribute('aria-hidden','true');if(searchInput)searchInput.value='';renderSearch('');}document.getElementById('searchOpen')?.addEventListener('click',openSearch);document.getElementById('searchClose')?.addEventListener('click',closeSearch);document.getElementById('searchCloseBtn')?.addEventListener('click',closeSearch);document.addEventListener('keydown',e=>{if(e.key==='Escape')closeSearch();});
  function renderSearch(query){if(!searchResults)return;const q=query.trim().toLowerCase();const matches=q?posts.filter(p=>[p.title,p.excerpt,p.categoryLabel].join(' ').toLowerCase().includes(q)):[];searchResults.innerHTML=matches.length?matches.map(p=>`<a class="search-result" href="article.html?id=${p.id}"><span class="search-result-cat">${p.categoryLabel}</span><strong>${p.title}</strong><small>${p.date} · ${p.read}</small><span>↗</span></a>`).join(''):`<p class="search-empty">${q?'没有找到相关内容，换个关键词试试。':'输入关键词，找到一篇想读的文章。'}</p>`;}searchInput?.addEventListener('input',e=>renderSearch(e.target.value));
  document.getElementById('newsletterForm')?.addEventListener('submit',e=>{e.preventDefault();const email=document.getElementById('email'),note=document.getElementById('formNote');if(!email.value)return;note.textContent='订阅成功！下一封信很快会抵达。';note.classList.add('is-success');email.value='';});
  const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('is-visible');observer.unobserve(entry.target);}}),{threshold:.12});document.querySelectorAll('.reveal').forEach(el=>observer.observe(el));
})();
